server:
  port: 8084

spring:
  application:
    name: ai-service
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000  # 구글 서버와 연결할 때 최대 3초 대기
            readTimeout: 10000    # 구글이 답변을 줄 때까지 최대 10초 대기

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

gemini:
  api-key: ${GEMINI_API_KEY}
  url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent